fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "go@create.me"
        sender_name: "Creator 2018"

    registration:
        form:
            name: my_app_user_registration
            type: App\Form\RegistrationFormType
        confirmation:
            enabled: false
            from_email:
                address: my_username@gmail.com
                sender_name: Demo registration